version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8089:8089
    depends_on: 
      - api

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
